name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '32 * * * *'
      
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
$1$2if [ -f go.mod ]; then
$2  go mod tidy
$2else
$2  echo "No go.mod, skipping module tidy"
$2fi

    - name: Generate README
      run: |
        if [ -f go.mod ]; then
          go run main.go
        else
          GO111MODULE=off go run main.go
        fi

    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "Updated content" || exit 0
        git push
